LineageOS-20:
  script:
    - git clone https://github.com/HowWof/android_kernel_realme_mt6785.git kernel -b LineageOS-20
    - cd kernel
    - git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang.git clang
    - make O=out ARCH=arm64 lineage-nashc_defconfig
    - PATH="${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}"

LineageOS-20-Polly:
  script:
    - git clone https://github.com/HowWof/android_kernel_realme_mt6785.git kernel -b LineageOS-20-Polly
    - cd kernel
    - git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang.git clang
    - make O=out ARCH=arm64 lineage-nashc_defconfig
    - PATH="${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}"

Zenitsu:
  script:
    - git clone https://github.com/Killerpac/android_kernel_realme_mt6785 kernel -b zenitsu
    - cd kernel
    - git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang.git clang
    - make O=out ARCH=arm64 lineage-nashc_defconfig
    - PATH="${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}"

Zenitsu-Polly:
  script:
    - git clone https://github.com/HowWof/android_kernel_realme_mt6785.git kernel -b Zenitsu-Polly
    - cd kernel
    - git clone --depth=1 https://gitlab.com/Panchajanya1999/azure-clang.git clang
    - make O=out ARCH=arm64 lineage-nashc_defconfig
    - PATH="${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}:${PWD}/clang/bin:${PATH}"

KSU:
  script:
    - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main